services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yml:/etc/loki/loki-config.yml
      - ./data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - monitoring
