services:
  landing-page:
    image: nginx:alpine
    container_name: homelab-landing
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - monitoring
