services:
  ntopng:
    image: ntop/ntopng:stable
    container_name: ntopng
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - ./config/ntopng.conf:/etc/ntopng/ntopng.conf:ro
      - ./data:/var/lib/ntopng
      - ./lib:/var/lib/ntopng/rrd
    command:
      - "/etc/ntopng/ntopng.conf"
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=${TZ:-America/New_York}
